### ISSUE TITLE
display(): "Stash to cloudant" can't edit or delete connection

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#107]
As a `<user type>`, I want to `<task>` so that `<goal>` (make this the title)

**Comment by DTAIEB** [comment]
If we want to keep this feature for 1.0, I agree being able to edit or delete connections is a must for 1.0.
In PR #167, I've made changes to simplify the design. Instead of immediately bringing a dialog box to select a connection, the list of connections is now in the cell output with button to edit and delete them.

![image](https://cloud.githubusercontent.com/assets/4912140/23344598/633fc948-fc4d-11e6-9d43-4cd1eba677ca.png)
