### ISSUE TITLE
display(): Add new [Cloudant] connection misc issues

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#109]
- Typo in line 10: `<<userIndentifier>>`
- the `label` and `plan` properties in the input are irrelevant and should be removed
- you are assuming that environment variable `VCAP_SERVICES`  is defined. However, this is only the case if a Cloudant instance is bound to an application. If the service is not bound to an app, the connection information is only available through the service credentials.
- the connection information should not be saved unless it has been validated successfully.

**Comment by DTAIEB** [comment]
Fix in PR #167 
There is no reliable way of validating the connection (without actually writing data which is too intrusive). Beside, I'm not sure connection validation on save is necessary anymore, since an error will be displayed during actual writing and user can now edit the connection to fix it.
