### ISSUE TITLE
display() barchart (Bokeh renderer): invalid aggregation function is displayed in Y axis label

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#183]
0.85:

```
import pixiedust
df=pixiedust.sampleData(6)
display(df)
```

* Select bar chart 
* Configure the options as follows:
  *  _keys_ : `STATE`
  * _values_: `PRICE`
 * _aggregation_: pick any

* Choose _Bokeh_ as renderer
* Inspect the Y axis label

### Expected behavior

The label should reflect the currently selected aggregation (e.g. `Avg(Price)`). 

### Actual behavior

For me the label always displays `Sum(Price)`.

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/b94f994d68deb38d9de77b8aa60e775724e574a9

**Comment by mikebroberg** [comment]
Testing!

**Comment by mikebroberg** [comment]
OK. Now it's not showing the wrong label because it is no longer showing an aggregation -- just the plain label of `PRICE`.

Adding aggregations to the Y axis would mean making this update for all chart options, so perhaps this will be a feature for a 1.1 release?

For now, the solution is workable because I know what aggregation I picked.
